import type { GridSpec, RGB } from '../src/types'
import { resolveColorCodes } from '../src/lib/color'
import glyphData from './ocr-fixture-glyphs.json'

/**
 * Independent OCR test source: Pillow rasterized Arial 20/21px labels and 15px rulers.
 * These alpha masks are not imported by the application or generated by its templates.
 * Keeping the rendered masks makes this fixture reproducible without system fonts/Python.
 */
interface FixtureOptions {
  exceptionalCell?: number
  exceptionalCode?: string
  uniformCode?: 'D6' | 'D8'
  font?: 'cell' | 'holdout'
  exceptionalFont?: 'cell' | 'holdout'
  /** Overlay a faint 6-shaped shadow on the 8 to create a controlled ambiguous glyph. */
  exceptionalDigitBlend?: number
}

export function independentOcrFixture(withCoordinates: boolean, options: FixtureOptions = {}) {
  const pitch = 40
  const cols = 20
  const rows = 20
  const width = (cols + 2) * pitch
  const height = (rows + 2) * pitch
  const data = new Uint8ClampedArray(width * height * 4).fill(255)
  const grid: GridSpec = { offsetX: pitch, offsetY: pitch, cellW: pitch, cellH: pitch, cols, rows }
  const fill = (x0: number, y0: number, rgb: RGB) => {
    for (let y = y0; y < y0 + pitch; y++) for (let x = x0; x < x0 + pitch; x++) {
      const p = (y * width + x) * 4
      data[p] = rgb[0]; data[p + 1] = rgb[1]; data[p + 2] = rgb[2]
    }
  }
  const drawText = (text: string, centerX: number, centerY: number, kind: 'coordinate' | 'cell' | 'holdout', digitBlend = 0) => {
    const font = glyphData[kind] as Record<string, { width: number; height: number; alpha: string }>
    const glyphs = Array.from(text, (char) => ({ ...font[char], char }))
    const textWidth = glyphs.reduce((sum, glyph) => sum + glyph.width, 0) + glyphs.length - 1
    const textHeight = Math.max(...glyphs.map((glyph) => glyph.height))
    let x0 = Math.round(centerX - textWidth / 2)
    const y0 = Math.round(centerY - textHeight / 2)
    for (const glyph of glyphs) {
      const alpha = atob(glyph.alpha)
      const shadow = digitBlend && glyph.char === '8' ? atob(font['6'].alpha) : null
      for (let y = 0; y < glyph.height; y++) for (let x = 0; x < glyph.width; x++) {
        const own = alpha.charCodeAt(y * glyph.width + x) / 255
        const a = shadow ? own * (1 - digitBlend) + shadow.charCodeAt(y * glyph.width + x) / 255 * digitBlend : own
        const p = ((y0 + y) * width + x0 + x) * 4
        data[p] = Math.round(data[p] * (1 - a))
        data[p + 1] = Math.round(data[p + 1] * (1 - a))
        data[p + 2] = Math.round(data[p + 2] * (1 - a))
      }
      x0 += glyph.width + 1
    }
  }
  if (withCoordinates) {
    for (let col = 0; col < cols; col++) drawText(String(col + 1), pitch * (col + 1.5), pitch / 2, 'coordinate')
    for (let row = 0; row < rows; row++) drawText(String(row + 1), pitch / 2, pitch * (row + 1.5), 'coordinate')
  }
  const truth = new Int16Array(cols * rows)
  for (let row = 0; row < rows; row++) for (let col = 0; col < cols; col++) {
    const index = row * cols + col
    const exceptional = index === options.exceptionalCell
    const code = exceptional ? (options.exceptionalCode ?? 'X8') : options.uniformCode ?? (col % 2 === 0 ? 'D6' : 'D8')
    fill(pitch * (col + 1), pitch * (row + 1), [210, 210, 230])
    drawText(code, pitch * (col + 1.5), pitch * (row + 1.5), exceptional ? options.exceptionalFont ?? options.font ?? 'cell' : options.font ?? 'cell', exceptional ? options.exceptionalDigitBlend : undefined)
    truth[index] = resolveColorCodes(code, 'MARD').indices[0] ?? -1
  }
  return { img: { width, height, data } as ImageData, grid, truth }
}
